### ISSUE TITLE
播放视频时Crash!

### ISSUE THREAD

**Issue by spysoos** [xuexiangjys/XVideo#1]
``java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xuexiang.xvideodemo-1/base.apk", zip file "/data/app/com.xuexiang.xvideodemo-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.xuexiang.xvideodemo-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.xuexiang.xvideodemo-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.xuexiang.xvideodemo-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.xuexiang.xvideodemo-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.xuexiang.xvideodemo-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.xuexiang.xvideodemo-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.xuexiang.xvideodemo-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.xuexiang.xvideodemo-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.xuexiang.xvideodemo-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.xuexiang.xvideodemo-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.xuexiang.xvideodemo-1/lib/arm64, /data/app/com.xuexiang.xvideodemo-1/base.apk!/lib/arm64-v8a, /data/app/com.xuexiang.xvideodemo-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.xuexiang.xvideodemo-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.xuexiang.xvideodemo-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.xuexiang.xvideodemo-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.xuexiang.xvideodemo-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.xuexiang.xvideodemo-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.xuexiang.xvideodemo-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.xuexiang.xvideodemo-1/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.xuexiang.xvideodemo-1/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.xuexiang.xvideodemo-1/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.xuexiang.xvideodemo-1/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libijkffmpeg.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1562)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:177)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:188)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:229)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:225)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:216)
        at com.xiao.nicevideoplayer.NiceVideoPlayer.initMediaPlayer(NiceVideoPlayer.java:383)
        at com.xiao.nicevideoplayer.NiceVideoPlayer.start(NiceVideoPlayer.java:179)
        at com.xiao.nicevideoplayer.TxVideoPlayerController.onClick(TxVideoPlayerController.java:369)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
06-04 17:08:31.924 31267-31278/com.xuexiang.xvideodemo E/art: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
06-04 17:08:31.924 31267-31278/com.xuexiang.xvideodemo E/System: Uncaught exception thrown by finalizer
06-04 17:08:31.925 31267-31278/com.xuexiang.xvideodemo E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:954)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
        at java.lang.Thread.run(Thread.java:761)

**Comment by xuexiangjys** [comment]
so包没有找到，应该是arm64-v8a的CPU设备，需要在app的gradle里添加如下代码：
  defaultConfig {
       ...
        ndk {
            abiFilters 'armeabi', 'armeabi-v7a', 'x86'
        }
    }

**Comment by spysoos** [comment]
仍然崩溃，不过这个不算是这个库的bug
